dist: trusty
sudo: required

language: c

cache:
  apt: true

compiler:
  - gcc-5
  - clang-3.8

git:
  submodules: false

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - clang-3.8

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - make && make test
